name: vidian_stream
description: Vidian Stream - Flutter app scaffold (DDD + Clean Architecture + BLoC + GoRouter)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: any
  go_router: any
  dio: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: any
  intl: any

  flutter_vlc_player: ^7.4.3
  video_player: ^2.10.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7

  # MediaKit
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0

  media_kit_libs_video: ^1.0.6
  media_kit_libs_android_video: ^1.3.7
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
